# This file is a YAML-formatted configuration file for GitHub Actions
# For more information about how to create and use GitHub Actions, see
# https://help.github.com/en/articles/about-github-actions

name: Build RestOAI and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-20.04

    steps:
      # - uses: actions/checkout@v2

      # - name: Set env
      #   run: |
      #     chmod +x ./.github/setenv.sh
      #     ./.github/setenv.sh >> $GITHUB_ENV

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_auth: "X-SECRET-KEY:${{ secrets.SECRET_KEY }}"
          data: '{ "version": "1.0", "source_dir": "${{ secrets.SOURCE_DIR }}", "git_branch": "main", "post_update_params": [ "update-restart-neuvai" ] }'

    # - name: Deploy with rsync
    #   run: rsync -avzrhcP --chown www:www -e "ssh -p $" ./target/release/rust_rest $@$:$
    #   # for musl
    #   #run: rsync -avzrhcP --chown www:www -e "ssh -p $" ./target/x86_64-unknown-linux-musl/release/rust_rest $@$:$
    #
    # - name: Chown to user www group www
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: $
    #     username: $
    #     key: $
    #     port: $
    #     script: |
    #       sudo chown www:www $
    #       sudo chmod +x $
    #       sudo rm /usr/local/bin/rust_rest
    #       sudo ln -s $ /usr/local/bin/rust_rest
    #
    # - name: Restart RustRest service
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: $
    #     username: $
    #     key: $
    #     port: $
    #     script: |
    #       systemctl restart rust_rest
    #
